### ISSUE TITLE
Browse button to select an image is missing in recent activity and signatures

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6374]
## Issue

When Plugin signatures is enabled with Advanced Editor, browsing to profile/signature to upload an image to the signature is missing the browse button

## Signatures Screen
![signatures](https://user-images.githubusercontent.com/31856281/34739973-ff042444-f54b-11e7-94f5-860064f1cd43.png)

Similar case in Recent Activity Page /activity

## Recent Activity Screen
![activity](https://user-images.githubusercontent.com/31856281/34740049-26b94cf8-f54c-11e7-90d0-0ca9be9a793d.png)

## Normal Behaviour

![normal](https://user-images.githubusercontent.com/31856281/34740156-708a179a-f54c-11e7-8978-9653c4540db9.png)

**Comment by LauraMakesArt** [comment]
This appears to also not have been resolved, (see: https://vanillaforums.teamwork.com/#tasks/8646770) I see the image upload on activity on profiles, now, but not on recent activity, or when creating polls.

**Comment by charrondev** [comment]
Instead of going with the approach of manually adding image-upload why not just have it on by default I see 10+ places where we want it and can't think of many where we don't want it. 

@linc Do you know where we would *not* to spawn the editor without the image upload? As I understand it will still get filtered out by permission if not allowed.

**Comment by charrondev** [comment]
After speaking with Todd, this will be added everywhere as a default param.
