### ISSUE TITLE
Cannot build Boilerplate Theme

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8381]
I suspect this is the wrong place for boilerplate theme feedback but I wouldn't know any better place. The GitHub link points to https://github.com/vanilla/themes which is a private repo. Therefore I post my issue here...

I've just installed (with yarn) the current boilerplate theme (version 1.1.2, updated 6 days ago).
In my composer.json I have `"vanilla/vanilla-cli": "*",` and I ran `composer update` to make sure that I have the most current version of the Vanilla CLI tool installed. The version number is 1.6.1 or 1.6.3 - not sure: I find both version numbers in my composer.lock file.

When I run `vanilla build --vanillasrc=../../` I get the following messages:

~~~
/home/rj/.composer/vendor/vanilla/vanilla-cli/node_modules/natives/index.js:137
    fn(nm.exports, cachingRequire, nm, nm.filename)
    ^
ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/rj/.composer/vendor/vanilla/vanilla-cli/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/rj/.composer/vendor/vanilla/vanilla-cli/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/rj/.composer/vendor/vanilla/vanilla-cli/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
~~~

**Comment by charrondev** [comment]
Came across this recently. We need to tag a new release for vanilla CLI. Node 10.15 shipped a change that broke gulp, which is used in that build. The intention is to support Node 10 which is why I got a fix merged but didn’t tag the release.

I’ve tagged it now as v1.6.2 so go grab that and it should fix the issue.

**Comment by R-J** [comment]
I found no Vanilla CLI 1.6.2. Trying to update it with composer by directly using ^1.6.2 results in " The requested package vanilla/vanilla-cli ^1.6.2 exists as vanilla/vanilla-cli[1.6.0, 1.6.1,"

I have upgraded the yarn package to 1.1.4 but that had changed nothing. I still get the same error message.

I do not know if I simply understood you wrong and you already gave the solution. I'm not used to all those build-tools, sorry.
